### ISSUE TITLE
split spritesheet - Syntax Error

### ISSUE THREAD

**Issue by SwissKiss** [Pathoschild/stardew-mod-dump-utils#1]
Hi,

I am sorry in advance for any stupid question being ask as I am a real noob when it comes down to programming languages... but I am unsure what does errors mean in your script:

![grafik](https://user-images.githubusercontent.com/60291017/222836655-c08a64f5-9e03-44e5-8826-4d8febc3bcc1.png)

I configured the settings under "Configuration" and it just throws these errors... thank you for your help.

**Comment by Pathoschild** [comment]
Hi! Can you post a screenshot of the full window with the parts you edited visible?
