### ISSUE TITLE
This script file seems to have some issues running on version 1.6

### ISSUE THREAD

**Issue by asqwedcxz741** [Pathoschild/stardew-mod-dump-utils#2]
I am using your script: translate event files.
Because my English is not very good, I referred to translation software to have a conversation with you. I am trying to make my question appear clear and accurate.

Perhaps my usage method is incorrect. When I change the configuration to open different JSON, the script always prompts me

 [Can't part this file as an event dictionary. The file must contain either a flat JSON object (i.e. Load format), or an object with only an Entries property containing a flat JSON object (i.e. EditData with FromFile format)]

I checked the specific error data and it seems to always appear in the first symbol of the format, which is: []

Here are some screenshots provided to you, and I would like to know if there is a solution. This is just an example, in fact, in different JSON files, there is always an error on this symbol in the first one.

![QQ截图20240326152443](https://github.com/Pathoschild/StardewScripts/assets/46841966/5d9230ad-6d6e-4a2d-aa0c-ee50e9132c4b)
![QQ截图20240326152524](https://github.com/Pathoschild/StardewScripts/assets/46841966/61545c0c-55b4-4083-b082-8c423cfe012a)

Thank you for your efforts. When I played games, it was your work that made the valley better！

**Comment by Pathoschild** [comment]
Hi! The file needs to be [one of the formats listed in the readme](https://github.com/Pathoschild/StardewScripts/tree/main/translate-event-files#event-file-format). The quickest solution might be to copy your `Entries` block into the "raw event file" format, run the tool, then copy the modified text back into your `content.json`.

If you still need help, feel free to come ask in [#making-mods-general on the Stardew Valley Discord](https://smapi.io/community#Discord) and I'll help there.
